--UC-1
create database PayRoll_Service
use PayRoll_Service

--UC-2
CREATE TABLE Employee_Payroll(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NAME VARCHAR(20) NOT NULL,
SALARY FLOAT NOT NUll,
START_DATE DATE NOT NULL
)

--UC-3
INSERT INTO Employee_Payroll VALUES('Harini',15000,'2022-06-19')
INSERT INTO Employee_Payroll VALUES('Harshini',25000,'2022-06-01')
INSERT INTO Employee_Payroll VALUES('Pardhavi',20000,'2018-02-25')
INSERT INTO Employee_Payroll VALUES('SENTHIL',25000,'2021-01-01')
INSERT INTO Employee_Payroll VALUES('PRIYA',10000,'2018-01-01')
INSERT INTO Employee_Payroll VALUES('RAMYA',40000,'2019-01-01')
INSERT INTO Employee_Payroll VALUES('LALITHA',30000,'2020-01-01')

--UC-4
SELECT * FROM Employee_Payroll

--UC-5
SELECT NAME,SALARY FROM Employee_Payroll WHERE NAME='Harini'
SELECT * FROM Employee_Payroll WHERE START_DATE BETWEEN '2021-06-01' AND CURRENT_TIMESTAMP

--UC-6
--ALTER TABLE employ_PayRoll ADD gender CHAR(10) CHECK (Gender IN ('M','F'));
ALTER TABLE Employee_Payroll ADD GENDER VARCHAR(10) NULL
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'F' WHERE NAME = 'Harini'
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'F' WHERE NAME = 'Harshini'
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'F' WHERE NAME = 'PRIYA'
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'F' WHERE NAME = 'Senthil'
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'F' WHERE NAME = 'RAMYA'
UPDATE EMPLOYEE_PAYROLL SET GENDER = 'F' WHERE NAME = 'LALITHA'

--UC7:
SELECT GENDER, SUM(SALARY) AS SUM_SALARY FROM EMPLOYEE_PAYROLL GROUP BY GENDER
SELECT GENDER, MIN(SALARY) AS MIN_SALARY FROM EMPLOYEE_PAYROLL GROUP BY GENDER
SELECT GENDER, MAX(SALARY) AS MAX_SALARY FROM EMPLOYEE_PAYROLL GROUP BY GENDER
SELECT GENDER, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEE_PAYROLL GROUP BY GENDER
SELECT GENDER, COUNT(GENDER) AS EMPLOYEE_COUNT FROM EMPLOYEE_PAYROLL GROUP BY GENDER

--UC8:
ALTER TABLE EMPLOYEE_PAYROLL ADD MOBILE DECIMAL NOT NULL DEFAULT(0)
UPDATE EMPLOYEE_PAYROLL SET MOBILE = 123 WHERE NAME = 'Harini'
UPDATE EMPLOYEE_PAYROLL SET MOBILE = 456 WHERE NAME = 'Harshini'
UPDATE EMPLOYEE_PAYROLL SET MOBILE = 789 WHERE NAME = 'PRIYA'
UPDATE EMPLOYEE_PAYROLL SET MOBILE = 1011 WHERE NAME = 'LALITHA'
ALTER TABLE EMPLOYEE_PAYROLL ADD ADDRESS VARCHAR(100) NOT NULL DEFAULT(''), DEPARTMENT VARCHAR(50) NOT NULL DEFAULT('')
UPDATE EMPLOYEE_PAYROLL SET ADDRESS = 'A',DEPARTMENT = 'Production' WHERE NAME = 'Harini'
UPDATE EMPLOYEE_PAYROLL SET ADDRESS = 'B',DEPARTMENT = 'Administration' WHERE NAME = 'Harshini'
UPDATE EMPLOYEE_PAYROLL SET ADDRESS = 'C',DEPARTMENT = 'IT_Support' WHERE NAME = 'PRIYA'
UPDATE EMPLOYEE_PAYROLL SET ADDRESS = 'D',DEPARTMENT = 'Production' WHERE NAME = 'LALITHA'

--UC9:
ALTER TABLE EMPLOYEE_PAYROLL ADD BASIC_PAY FLOAT NOT NULL DEFAULT(0), DEDUCTIONS FLOAT NOT NULL DEFAULT(0),
TAXABLE_PAY FLOAT NOT NULL DEFAULT(0), NET_PAY FLOAT NOT NULL DEFAULT(0)
UPDATE EMPLOYEE_PAYROLL SET BASIC_PAY = 10000,DEDUCTIONS = 200,TAXABLE_PAY = 200,NET_PAY = 9600 WHERE ID = 1
UPDATE EMPLOYEE_PAYROLL SET BASIC_PAY = 10000,DEDUCTIONS = 200,TAXABLE_PAY = 200,NET_PAY = 9600 WHERE ID = 2
UPDATE EMPLOYEE_PAYROLL SET BASIC_PAY = 15000,DEDUCTIONS = 200,TAXABLE_PAY = 200,NET_PAY = 14600 WHERE ID = 3
UPDATE EMPLOYEE_PAYROLL SET BASIC_PAY = 20000,DEDUCTIONS = 200,TAXABLE_PAY = 200,NET_PAY = 19600 WHERE ID = 4

--UC10:
INSERT INTO EMPLOYEE_PAYROLL VALUES('Terisa',15000,'2021-01-01','F',9876543210,'Chennai','Sales&Marketing',15000,200,200,14600)
UPDATE EMPLOYEE_PAYROLL SET NAME = 'Harshini' WHERE ID = 5
UPDATE EMPLOYEE_PAYROLL SET DEPARTMENT = 'Sales' WHERE NAME = 'Terissa'
INSERT INTO EMPLOYEE_PAYROLL VALUES('Terissa',15000,'2021-01-01','F',9876543210,'Chennai','Marketing',15000,200,200,14600)


Select * from Employee_Payroll

INSERT INTO EMPLOYEE_PAYROLL VALUES('Terisa',15000,'2021-01-01','F',9876543210,'Chennai','Sales&Marketing',15000,200,200,14600)
UPDATE EMPLOYEE_PAYROLL SET NAME = 'Terissa' WHERE ID = 5
UPDATE EMPLOYEE_PAYROLL SET DEPARTMENT = 'Sales' WHERE NAME = 'Terissa'
INSERT INTO EMPLOYEE_PAYROLL VALUES('Terissa',15000,'2021-01-01','F',9876543210,'Chennai','Marketing',15000,200,200,14600)




--UC-11
--FOR UC-10- ER DIAGRAM CREATED FOR BELOW TABLES
-- cREATING VOMPANY TABLE

--CREATING COMPANIES TABLE
CREATE TABLE COMPANIES(
COMPANY_ID INT IDENTITY(101,1) PRIMARY KEY NOT NULL,
COMPANY_NAME VARCHAR(25) NOT NULL)

SELECT * FROM COMPANIES

INSERT INTO COMPANIES VALUES ('ABC')
INSERT INTO COMPANIES VALUES ('XYZ')

--CREATING EMPLOYEE_DETAILS TABLE
CREATE TABLE EMPLOYEES_DETAILS(
EMP_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NAME VARCHAR(50) NOT NULL,
GENDER VARCHAR(2) NOT NULL,
PHONE FLOAT NOT NULL,
EMAIL VARCHAR(50) NOT NULL)

select * from EMPLOYEES_DETAILS

ALTER TABLE EMPLOYEES_DETAILS ADD START_DATE DATE NOT NULL
ALTER TABLE EMPLOYEES_DETAILS ADD COMPANY_ID INT NOT NULL DEFAULT(0)

INSERT INTO EMPLOYEES_DETAILS VALUES('Terissa','F',9087654321,'terissa@gmail.com','2018-05-01')
INSERT INTO EMPLOYEES_DETAILS VALUES('Harini','M',9807654321,'harini@gmail.com','2022-05-10')
INSERT INTO EMPLOYEES_DETAILS VALUES('Harshini','M',9123456780,'harshini@gmail.com','2022-05-10')
INSERT INTO EMPLOYEES_DETAILS VALUES('Poonam','M',8907651234,'poonam@gmail.com','2021-10-05')
UPDATE EMPLOYEES_DETAILS SET COMPANY_ID = 101
UPDATE EMPLOYEES_DETAILS SET START_DATE = '2022-05-10' WHERE NAME = 'Harshini'

Select * from EMPLOYEES_DETAILS

--CREATING DEPARTMENT_DETAILS TABLE
CREATE TABLE DEPARTMENT_DETAILS(
DEPT_ID INT IDENTITY(11,1) PRIMARY KEY NOT NULL,
DEPT_NAME VARCHAR(25) NOT NULL)

INSERT INTO DEPARTMENT_DETAILS VALUES('Administration'),('Sales'),('Marketing'),('Production')

--CREATING EMPLOYEE_ADDRESS TABLE
CREATE TABLE EMP_ADDRESS(
NAME VARCHAR(50) PRIMARY KEY NOT NULL,
ADDRESS VARCHAR(25) NOT NULL,
CITY VARCHAR(25) NOT NULL,
STATE VARCHAR(25) NOT NULL,
ZIP_CODE INT NOT NULL)

select * from EMP_ADDRESS

INSERT INTO EMP_ADDRESS VALUES('Terissa','15C','Chennai','Tamil Nadu',600001)
INSERT INTO EMP_ADDRESS VALUES('Harini','11A','Komarapalayam','Tamil Nadu',654321)
INSERT INTO EMP_ADDRESS VALUES('swathi','12D','Coimbatore','Tamil Nadu',645231)
INSERT INTO EMP_ADDRESS VALUES('sunita','14C','Dindigul','Tamil Nadu',632154)

--CREATING EMPLOYEE_SALARY TABLE
CREATE TABLE EMP_SALARY(
EMP_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NAME VARCHAR(50) NOT NULL,
BASIC_PAY FLOAT NOT NULL,
DEDUCTIONS FLOAT NOT NULL,
TAXABLE_PAY FLOAT NOT NULL,
INCOME_TAX FLOAT NOT NULL,
NET_PAY FLOAT NOT NULL)

INSERT INTO EMP_SALARY VALUES('A',50000,1000,1000,2000,46000)
INSERT INTO EMP_SALARY VALUES('B',30000,1000,1000,2000,26000)
INSERT INTO EMP_SALARY VALUES('C',40000,1000,1000,2000,36000)
INSERT INTO EMP_SALARY VALUES('D',50000,1000,1000,2000,46000)

select * from EMP_SALARY

--CREATING EMPLOYEE_DEPARTMENT TABLE
CREATE TABLE EMP_DEPARTMENT(
EMP_ID INT NOT NULL,
EMP_NAME VARCHAR(25) NOT NULL,
DEPT_ID INT NOT NULL,
DEPT_NAME VARCHAR(25) NOT NULL)

 select * from EMP_DEPARTMENT

INSERT INTO EMP_DEPARTMENT VALUES(1,'Terissa',12,'Sales'),(1,'Terissa',13,'Marketing'),(2,'Elavarasu',14,'Production'),(3,'Nantha',14,'Production'),(4,'Senthil',11,'Administration')


--ADDING CONSTRAINTS TO THE TABLES

ALTER TABLE EMPLOYEES_DETAILS ADD CONSTRAINT FK_COMP_ID FOREIGN KEY(COMPANY_ID) REFERENCES COMPANIES(COMPANY_ID)
ALTER TABLE EMP_SALARY ADD CONSTRAINT FK_EMP_ID FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEES_DETAILS(EMP_ID)
ALTER TABLE EMPLOYEES_DETAILS ADD CONSTRAINT FK_NAME FOREIGN KEY(NAME) REFERENCES EMP_ADDRESS(NAME)
ALTER TABLE EMP_DEPARTMENT ADD CONSTRAINT FK_EMP_DEPT_ID FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEES_DETAILS(EMP_ID)
ALTER TABLE EMP_DEPARTMENT ADD CONSTRAINT FK_DEPT_ID FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT_DETAILS(DEPT_ID)

SELECT GENDER,SUM(BASIC_PAY) AS SALARY_SUM FROM EMPLOYEES_DETAILS ED INNER JOIN EMP_SALARY ES ON ES.EMP_ID = ED.EMP_ID GROUP BY GENDER
SELECT GENDER,MIN(BASIC_PAY) AS MIN_SALARY FROM EMPLOYEES_DETAILS ED INNER JOIN EMP_SALARY ES ON ES.EMP_ID = ED.EMP_ID GROUP BY GENDER
SELECT GENDER,MAX(BASIC_PAY) AS MAX_SALARY FROM EMPLOYEES_DETAILS ED INNER JOIN EMP_SALARY ES ON ES.EMP_ID = ED.EMP_ID GROUP BY GENDER
SELECT GENDER,AVG(BASIC_PAY) AS AVG_SALARY FROM EMPLOYEES_DETAILS ED INNER JOIN EMP_SALARY ES ON ES.EMP_ID = ED.EMP_ID GROUP BY GENDER
SELECT GENDER,COUNT(GENDER) AS EMP_COUNT FROM EMPLOYEES_DETAILS ED INNER JOIN EMP_SALARY ES ON ES.EMP_ID = ED.EMP_ID GROUP BY GENDER

SELECT ED.EMP_ID,ED.NAME,GENDER,PHONE,START_DATE,BASIC_PAY,DEDUCTIONS,TAXABLE_PAY,INCOME_TAX,NET_PAY FROM EMPLOYEES_DETAILS ED INNER JOIN EMP_SALARY ES 
ON ED.EMP_ID = ES.EMP_ID WHERE START_DATE BETWEEN '2022-01-01' AND CURRENT_TIMESTAMP

SELECT ED.NAME,BASIC_PAY FROM EMPLOYEES_DETAILS ED INNER JOIN EMP_SALARY ES ON ED.EMP_ID = ES.EMP_ID WHERE ED.NAME = 'Harini'

SELECT * FROM COMPANIES
SELECT * FROM EMPLOYEES_DETAILS
SELECT * FROM EMP_ADDRESS
SELECT * FROM DEPARTMENT_DETAILS
SELECT * FROM EMP_SALARY
SELECT * FROM EMP_DEPARTMENT

SELECT C.COMPANY_ID,COMPANY_NAME,DD.DEPT_ID,DD.DEPT_NAME,ED.EMP_ID,EA.NAME,GENDER,PHONE,EMAIL,START_DATE,ADDRESS,CITY,STATE,ZIP_CODE,BASIC_PAY,NET_PAY FROM
COMPANIES C INNER JOIN EMPLOYEES_DETAILS ED ON C.COMPANY_ID = ED.COMPANY_ID INNER JOIN EMP_DEPARTMENT EMPD ON ED.EMP_ID = EMPD.EMP_ID INNER JOIN DEPARTMENT_DETAILS DD
ON DD.DEPT_ID = EMPD.DEPT_ID INNER JOIN EMP_ADDRESS EA ON EA.NAME = ED.NAME INNER JOIN EMP_SALARY ES ON ES.EMP_ID = ED.EMP_ID

ALTER TABLE EMP_DEPARTMENT ALTER COLUMN EMPLOYEE_ID VARCHAR(25)

ALTER TABLE EMPLOYEE_DETAIL ALTER COLUMN COMPANY_NAME VARCHAR(30)
SELECT * FROM EMPLOYEE_DETAIL

--UC1 ADO.NET
--PROCEDURE FOR CHECKING CONNECTIVITY
GO
CREATE PROCEDURE ConnectivityCheck
AS
BEGIN
SELECT * FROM EMPLOYEE_PAYROLL
END

--PROCEDURE FOR ADD DATA TO THE TABLE
GO
CREATE OR ALTER PROCEDURE [dbo].[SpAddEmployeeDetails]
(@NAME VARCHAR(25),
@SALARY FLOAT,
@START_DATE DATE,
@GENDER VARCHAR(10),
@MOBILE DECIMAL,
@ADDRESS VARCHAR(100),
@DEPARTMENT VARCHAR(50),
@BASIC_PAY FLOAT,
@DEDUCTIONS FLOAT,
@TAXABLE_PAY FLOAT,
@NET_PAY FLOAT)
AS
BEGIN
INSERT INTO EMPLOYEE_PAYROLL VALUES(@NAME,@SALARY,@START_DATE,@GENDER,@MOBILE,@ADDRESS,@DEPARTMENT,@BASIC_PAY,@DEDUCTIONS,@TAXABLE_PAY,@NET_PAY)
END

SELECT * FROM EMPLOYEE_PAYROLL

--PROCEDURE FOR UPDATING DATA IN THE TABLE
GO
CREATE OR ALTER PROCEDURE [dbo].[UpdateEmployee_Payroll]
(@NAME VARCHAR(25),
@BASIC_PAY FLOAT)
AS
BEGIN
UPDATE EMPLOYEE_PAYROLL SET BASIC_PAY = @BASIC_PAY WHERE NAME = @NAME
END

--PROCEDURE
GO
CREATE OR ALTER PROCEDURE [dbo].[DeleteEmployee_Payroll]
(@NAME VARCHAR(25))
AS
BEGIN
DELETE FROM EMPLOYEE_PAYROLL WHERE NAME = @NAME
END

